# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Parser-YahooRESTGeocode
version:      0.2
version_from: YahooRESTGeocode.pm
installdirs:  site
requires:
    XML::Parser:                   2.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
